herbco_env/herbco/apps/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView ,LogoutView

from profiles.views import (
    UserLoginView,
    UserCreateView,
    DistributorCreateView,
    DistributorPendingListView,
    confirm_distributor, # FBV
    DistributorItemsListView,
)
urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', UserCreateView.as_view(), name='register'),
    url(r'^distributors/create/$', DistributorCreateView.as_view(), name='distributor_create'),
    url(r'^distributors/pending/$', DistributorPendingListView.as_view(), name='distributors'),
    url(r'^distributors/pending/confirm/$', confirm_distributor, name='distributor_confirm'),
    url(r'^distributors/my-items/$', DistributorItemsListView.as_view(), name='distributor_items'),

]

herbco_env/herbco/apps/shop/urls.py
from django.conf.urls import url

from shop.views import (
    HomeView,
    ItemCreateView,
    ItemDetailView,
    ItemPendingListView,
    ShoppingCartListView,
    ContactUsTemplateView,
    confirm_item,
    confirm_u_item,
    add_to_cart,
    delete_from_cart,
    CategoryListView,
    ItemUpdatingListView,
    search,
    ItemUpdateView,
    CheckOut,
    item_delete,
    ItemDeletedListView,
    confirm_deleted_item,
    StaticsListView,
    checkout_final,
    MyOrdersListView,
    comment,
    FeedBacksListView,
    update_quantity,
    add_again,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/$', search, name='search'),
    url(r'^item/create/$', ItemCreateView.as_view(), name='create'),
    url(r'^item/item_delete/(?P<pk>\d+)/$', item_delete, name='item_delete'),
    url(r'^item/add_again/(?P<pk>\d+)/$', add_again, name='add_again'),
    url(r'^item/update/(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    url(r'^item/add/(?P<id>\d+)/$', add_to_cart, name='add_to_cart'),
    url(r'^item/delete/(?P<id>\d+)/$', delete_from_cart, name='delete_from_cart'),
    url(r'^item/(?P<slug>[-\w]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^items/pending/$', ItemPendingListView.as_view(), name='pending_items'),
    url(r'^items/updated/$', ItemUpdatingListView.as_view(), name='updated_items'),
    url(r'^items/deleted/$', ItemDeletedListView.as_view(), name='deleted_items'),
    url(r'^item/pending/confirm/$', confirm_item, name='confirm_item'),
    url(r'^item/updated/confirm/$', confirm_u_item, name='confirm_u_item'),
    url(r'^item/deleted/confirm/$', confirm_deleted_item, name='confirm_deleted_item'),
    url(r'^update_quantity/$', update_quantity, name='update_quantity'),
    url(r'^statics/$', StaticsListView.as_view(), name='statics'),
    url(r'^cart/$', ShoppingCartListView.as_view(), name='cart'),
    url(r'^cart/checkout/$', CheckOut.as_view(), name='checkout'),
    url(r'^cart/checkout/final/$', checkout_final, name='checkout_final'),
    url(r'^contact-us/$', ContactUsTemplateView.as_view(), name='contact_us'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryListView.as_view(), name='categories'),
    url(r'^my_orders/$', MyOrdersListView.as_view(), name='my_orders'),
    url(r'^feedbacks/$', FeedBacksListView.as_view(), name='feedbacks'),
    url(r'^comment/done/$', comment, name='comment'),
]

herbco_env/herbco/herbco/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# For development
from django.conf import settings
from django.conf.urls.static import static
# For development

urlpatterns = [
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^users/', include('profiles.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

herbco_env/herbco/apps/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django_countries.fields import CountryField

ADMIN       = '1'
MANAGER     = '2'
DISTRIBUTOR = '3'
CUSTOMER    = '4'

USER_TYPE_CHOICES = (
    (ADMIN, 'Admin'),
    (MANAGER, 'Manager'),
    (DISTRIBUTOR, 'Distributor'),
    (CUSTOMER, 'Customer'),
)

class User(AbstractUser):
    user_type           = models.CharField(max_length=2, choices=USER_TYPE_CHOICES, default=CUSTOMER)
    adress              = models.CharField(max_length=220, null=True, blank=True)
    postcode            = models.PositiveSmallIntegerField(null=True, blank=True)
    country             = CountryField()

    def __str_(self):
        return self.username

class Distributor(models.Model):
    user                = models.ForeignKey(User, on_delete=models.CASCADE)
    brand               = models.CharField(max_length=100)
    ceo_name            = models.CharField(max_length=100)
    average_earnings    = models.PositiveIntegerField()
    company_created_At  = models.DateField(auto_now=False, auto_now_add=False)
    is_approveled       = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

herbco_env/herbco/apps/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms.extras import SelectDateWidget

from profiles.models import User, Distributor
from shop.models import ShoppingCart
from django_countries.widgets import CountrySelectWidget

class RegisterForm(forms.ModelForm):
    username    = forms.CharField(help_text="")
    password1   = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2   = forms.CharField(label='Password Again', widget=forms.PasswordInput)
    email       = forms.EmailField(label='Email Adress', required=True)

    class Meta:
        model = User
        fields = [

            'last_name',
            'first_name',
            'email',
            'username',
            'adress',
            'postcode',
            'country',

        ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("This email already exists!")
        return email

    def clean_password2(self):
            password1 = self.cleaned_data.get("password1")
            password2 = self.cleaned_data.get("password2")
            if password1 and password2 and password1 != password2:
                raise forms.ValidationError("Password does not match!")
            return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            shopcart = ShoppingCart.objects.create(owner=user)
            shopcart.save()
        return user

class DistributorCreateForm(forms.ModelForm):
    company_created_At = forms.DateField(widget=SelectDateWidget(years=range(1970, 2018)))

    class Meta:
        model = Distributor
        fields = [
            'brand',
            'ceo_name',
            'average_earnings',
            'company_created_At',
        ]

herbco_env/herbco/apps/profiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import (
    FormView,
    CreateView,
    ListView,
    UpdateView,
)
from .models import Distributor
from shop.models import Item
from .forms import RegisterForm, DistributorCreateForm, Distributor

@login_required(redirect_field_name='/users/login')
def confirm_distributor(request):
    if request.method == 'POST':
        list_of_input_ids=request.POST.getlist('inputs')
        for dist_id in list_of_input_ids:
            distributor = get_object_or_404(Distributor, pk=dist_id)
            if 'reject_dist' in request.POST:
                distributor.delete()
            elif 'accept_dist' in request.POST:
                distributor.is_approveled = True
                distributor.user.user_type = '3'
                distributor.save()
                distributor.user.save()
    return HttpResponseRedirect('/users/distributors/pending/')

class UserLoginView(LoginView):
    template_name = 'profiles/login.html'

class UserCreateView(FormView):
    form_class = RegisterForm
    template_name = 'profiles/register.html'
    success_url = '/users/login'

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Successfully, You can login now.')
        return super(UserCreateView, self).form_valid(form)

class DistributorCreateView(LoginRequiredMixin, CreateView):
    form_class = DistributorCreateForm
    template_name = 'profiles/distributor_create.html'
    success_url = '/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super(DistributorCreateView, self).form_valid(form)

class DistributorPendingListView(LoginRequiredMixin, ListView):
    template_name = 'profiles/distributor_pending.html'
    queryset = Distributor.objects.filter(is_approveled=False)
    context_object_name = 'distributors'

    def get_context_data(self, *args, **kwargs):
        context = super(DistributorPendingListView, self).get_context_data(*args ,**kwargs)
        context['dist_count'] = Distributor.objects.filter(is_approveled=False).count()
        return context

class DistributorItemsListView(LoginRequiredMixin, ListView):
    template_name ="profiles/distributor_items.html"
    context_object_name = 'items'

    def get_queryset(self):
        if self.request.user.user_type == '3':
            queryset = self.request.user.distributor_set.first().item_set.all().filter(is_deleted=False)
        else:
            queryset = None
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(DistributorItemsListView, self).get_context_data(*args ,**kwargs)
        context['deleted_items'] = self.request.user.distributor_set.first().item_set.all().filter(is_deleted=True)
        return context

herbco_env/herbco/apps/profiles/templates/profiles/distributor_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-12 col-md-10 offset-md-1 col-lg-6 offset-lg-3">
  {% if user.user_type == '1' %}    <!-- If User is Admin -->
    <h4>You are ADMIN !!! <br>You can not register as Distrubor</h4>
  {% elif user.user_type == '2' %}  <!-- If User is Manager -->
    <h4>You are MANAGER !!! <br>You can not register as Distrubor</h4>
  {% elif user.user_type == '3' %}  <!-- If User is Distributor -->
    <h4>You are aldready DISTRIBUTOR !!! <br></h4>
  {% else %}                        <!-- If User is Customer -->
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-dark" type="submit">Register as Distributor</button>
  </form>
  {% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/profiles/templates/profiles/distributor_items.html
{% extends "base.html" %}
{% block content %}
<div class="col-7 mx-auto">
{% if request.user.user_type == '3' %}
    <div class="row">
      {% for item in items %}
        <div class="col-sm-3">
          <div class="card mb-4">
            <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
              <span>${{ item.price }}</span>
              <a href="{% url 'shop:update' item.pk%}" class="btn btn-primary pull-right">Edit
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% if deleted_items %}
    <h2>Deleted Items</h2> <br>
    {% endif %}
    <div class="row">
      {% for item in deleted_items %}
        <div class="col-sm-3">
          <div class="card mb-4">
            <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
              <span>${{ item.price }}</span>
              <a href="{% url 'shop:update' item.pk%}" class="btn btn-primary pull-right">Edit
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
{% else %}
  <h1>You are not distributor.</h1>
{% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/profiles/templates/profiles/distributor_pending.html
{% extends "base.html" %}
{% block content %}
  <div class="col-12">
    {% if user.user_type == '2' %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Brand</th>
          <th scope="col">Ceo Name</th>
          <th scope="col">Average Earnings</th>
          <th scope="col">Is Approveled ?</th>
        </tr>
      </thead>
      {% for distributor in distributors %}
      <form action="{% url 'users:distributor_confirm' %}" method="post">{% csrf_token %}
      <tbody>
        <tr>
          <th scope="row">{{ distributor.id }}</th>
          <td>{{ distributor.brand }}</td>
          <td>{{ distributor.ceo_name }}</td>
          <td>{{ distributor.average_earnings }}</td>
          <td>
            <input type="checkbox" name="inputs" value="{{distributor.pk}}"/>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <input class="btn btn-danger btn-right" name="reject_dist" type="submit" value="Reject Selected User">
    <input class="btn btn-dark btn-right pull-right" name="accept_dist" type="submit" value="Approvel Selected User">
    </form>
    {% else %}
      <h4>Only managers can access this page !</h4>
    {% endif %}
  </div>
{% endblock content %}

herbco_env/herbco/apps/profiles/templates/profiles/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-sm-12 col-md-10 offset-md-1 col-lg-6 offset-lg-3">
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
        <h4>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</h4>
        <br>
        {% else %}
        <h3>Please login to see this page.</h3>
        <br>
        {% endif %}
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-dark" type="submit" value="Log In" />
    <input type="hidden" name="next" value="{{ next }}" />
    </form>
    <br>
    <a href="{% url 'users:register' %}">Sign Up</a> ,If you do not have an account!
</div>

{% endblock content %}

herbco_env/herbco/apps/profiles/templates/profiles/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-sm-12 col-md-10 offset-md-1 col-lg-6 offset-lg-3">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark" type="submit">Register</button>
      </form>
      <br>
      <a href="{% url 'users:login' %}">Sign In</a> ,If you have an account!
    </div>
{% endblock content %}