herbco_env/herbco/apps/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView ,LogoutView

from profiles.views import (
    UserLoginView,
    UserCreateView,
    DistributorCreateView,
    DistributorPendingListView,
    confirm_distributor, # FBV
    DistributorItemsListView,
)
urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', UserCreateView.as_view(), name='register'),
    url(r'^distributors/create/$', DistributorCreateView.as_view(), name='distributor_create'),
    url(r'^distributors/pending/$', DistributorPendingListView.as_view(), name='distributors'),
    url(r'^distributors/pending/confirm/$', confirm_distributor, name='distributor_confirm'),
    url(r'^distributors/my-items/$', DistributorItemsListView.as_view(), name='distributor_items'),

]

herbco_env/herbco/apps/shop/urls.py
from django.conf.urls import url

from shop.views import (
    HomeView,
    ItemCreateView,
    ItemDetailView,
    ItemPendingListView,
    ShoppingCartListView,
    ContactUsTemplateView,
    confirm_item,
    confirm_u_item,
    add_to_cart,
    delete_from_cart,
    CategoryListView,
    ItemUpdatingListView,
    search,
    ItemUpdateView,
    CheckOut,
    item_delete,
    ItemDeletedListView,
    confirm_deleted_item,
    StaticsListView,
    checkout_final,
    MyOrdersListView,
    comment,
    FeedBacksListView,
    update_quantity,
    add_again,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/$', search, name='search'),
    url(r'^item/create/$', ItemCreateView.as_view(), name='create'),
    url(r'^item/item_delete/(?P<pk>\d+)/$', item_delete, name='item_delete'),
    url(r'^item/add_again/(?P<pk>\d+)/$', add_again, name='add_again'),
    url(r'^item/update/(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    url(r'^item/add/(?P<id>\d+)/$', add_to_cart, name='add_to_cart'),
    url(r'^item/delete/(?P<id>\d+)/$', delete_from_cart, name='delete_from_cart'),
    url(r'^item/(?P<slug>[-\w]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^items/pending/$', ItemPendingListView.as_view(), name='pending_items'),
    url(r'^items/updated/$', ItemUpdatingListView.as_view(), name='updated_items'),
    url(r'^items/deleted/$', ItemDeletedListView.as_view(), name='deleted_items'),
    url(r'^item/pending/confirm/$', confirm_item, name='confirm_item'),
    url(r'^item/updated/confirm/$', confirm_u_item, name='confirm_u_item'),
    url(r'^item/deleted/confirm/$', confirm_deleted_item, name='confirm_deleted_item'),
    url(r'^update_quantity/$', update_quantity, name='update_quantity'),
    url(r'^statics/$', StaticsListView.as_view(), name='statics'),
    url(r'^cart/$', ShoppingCartListView.as_view(), name='cart'),
    url(r'^cart/checkout/$', CheckOut.as_view(), name='checkout'),
    url(r'^cart/checkout/final/$', checkout_final, name='checkout_final'),
    url(r'^contact-us/$', ContactUsTemplateView.as_view(), name='contact_us'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryListView.as_view(), name='categories'),
    url(r'^my_orders/$', MyOrdersListView.as_view(), name='my_orders'),
    url(r'^feedbacks/$', FeedBacksListView.as_view(), name='feedbacks'),
    url(r'^comment/done/$', comment, name='comment'),
]

herbco_env/herbco/herbco/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# For development
from django.conf import settings
from django.conf.urls.static import static
# For development

urlpatterns = [
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^users/', include('profiles.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

herbco_env/herbco/apps/templates/include/nav.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'shop:home' %}"><b>Herb</b>Shopping</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form method="get" action="{% url 'shop:search' %}" class="form-inline">
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search" value="{{request.GET.search}}">
      <div class="form-group">
        <select name="category" class="form-control" id="sel1">
          <option value="0">You can choose a category</option>
          {% for category in categories %}
          <option value="{{category.pk}}">{{category.name}}</option>
          {% endfor %}
        </select>
      </div>
    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'shop:contact_us' %}">Contact Us</a></li>
      <li class="nav-item"></li>
    </ul>

    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Aranacak Kelimeyi Girin" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </form>
    -->

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      {% if user.user_type == '4' %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:cart' %}">
          {% if request.user.shopping_cart.first.items.all.count != 0 %}
          <span class="badge badge-pill badge-danger" style="margin-left:5px;">{{request.user.shopping_cart.first.items.all.count}}</span>
          {% endif %}
          <i class="fa fa-shopping-cart" aria-hidden="true"></i> Basket
        </a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user"></i> {{ request.user }} </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          {% if user.user_type == '4' %}
          <a class="dropdown-item" href="{% url 'shop:my_orders' %}">My Previous Orders</a>
          <div class="dropdown-divider"></div>
          {% endif %}
          <a class="dropdown-item" href="{% url 'users:logout' %}" style="color:red;">Çıkış Yap</a>
        </div>
      </li>
    </ul>
  </div>
  {% else %}
  <ul class="navbar-nav ml-auto">
    <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Sign In</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Sign Up</a></li>
  </ul>
  {% endif %}
</nav>