herbco_env/herbco/apps/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView ,LogoutView

from profiles.views import (
    UserLoginView,
    UserCreateView,
    DistributorCreateView,
    DistributorPendingListView,
    confirm_distributor, # FBV
    DistributorItemsListView,
)
urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', UserCreateView.as_view(), name='register'),
    url(r'^distributors/create/$', DistributorCreateView.as_view(), name='distributor_create'),
    url(r'^distributors/pending/$', DistributorPendingListView.as_view(), name='distributors'),
    url(r'^distributors/pending/confirm/$', confirm_distributor, name='distributor_confirm'),
    url(r'^distributors/my-items/$', DistributorItemsListView.as_view(), name='distributor_items'),

]

herbco_env/herbco/apps/shop/urls.py
from django.conf.urls import url

from shop.views import (
    HomeView,
    ItemCreateView,
    ItemDetailView,
    ItemPendingListView,
    ShoppingCartListView,
    ContactUsTemplateView,
    confirm_item,
    confirm_u_item,
    add_to_cart,
    delete_from_cart,
    CategoryListView,
    ItemUpdatingListView,
    search,
    ItemUpdateView,
    CheckOut,
    item_delete,
    ItemDeletedListView,
    confirm_deleted_item,
    StaticsListView,
    checkout_final,
    MyOrdersListView,
    comment,
    FeedBacksListView,
    update_quantity,
    add_again,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/$', search, name='search'),
    url(r'^item/create/$', ItemCreateView.as_view(), name='create'),
    url(r'^item/item_delete/(?P<pk>\d+)/$', item_delete, name='item_delete'),
    url(r'^item/add_again/(?P<pk>\d+)/$', add_again, name='add_again'),
    url(r'^item/update/(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    url(r'^item/add/(?P<id>\d+)/$', add_to_cart, name='add_to_cart'),
    url(r'^item/delete/(?P<id>\d+)/$', delete_from_cart, name='delete_from_cart'),
    url(r'^item/(?P<slug>[-\w]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^items/pending/$', ItemPendingListView.as_view(), name='pending_items'),
    url(r'^items/updated/$', ItemUpdatingListView.as_view(), name='updated_items'),
    url(r'^items/deleted/$', ItemDeletedListView.as_view(), name='deleted_items'),
    url(r'^item/pending/confirm/$', confirm_item, name='confirm_item'),
    url(r'^item/updated/confirm/$', confirm_u_item, name='confirm_u_item'),
    url(r'^item/deleted/confirm/$', confirm_deleted_item, name='confirm_deleted_item'),
    url(r'^update_quantity/$', update_quantity, name='update_quantity'),
    url(r'^statics/$', StaticsListView.as_view(), name='statics'),
    url(r'^cart/$', ShoppingCartListView.as_view(), name='cart'),
    url(r'^cart/checkout/$', CheckOut.as_view(), name='checkout'),
    url(r'^cart/checkout/final/$', checkout_final, name='checkout_final'),
    url(r'^contact-us/$', ContactUsTemplateView.as_view(), name='contact_us'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryListView.as_view(), name='categories'),
    url(r'^my_orders/$', MyOrdersListView.as_view(), name='my_orders'),
    url(r'^feedbacks/$', FeedBacksListView.as_view(), name='feedbacks'),
    url(r'^comment/done/$', comment, name='comment'),
]

herbco_env/herbco/herbco/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# For development
from django.conf import settings
from django.conf.urls.static import static
# For development

urlpatterns = [
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^users/', include('profiles.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

herbco_env/herbco/apps/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django_countries.fields import CountryField

ADMIN       = '1'
MANAGER     = '2'
DISTRIBUTOR = '3'
CUSTOMER    = '4'

USER_TYPE_CHOICES = (
    (ADMIN, 'Admin'),
    (MANAGER, 'Manager'),
    (DISTRIBUTOR, 'Distributor'),
    (CUSTOMER, 'Customer'),
)

class User(AbstractUser):
    user_type           = models.CharField(max_length=2, choices=USER_TYPE_CHOICES, default=CUSTOMER)
    adress              = models.CharField(max_length=220, null=True, blank=True)
    postcode            = models.PositiveSmallIntegerField(null=True, blank=True)
    country             = CountryField()

    def __str_(self):
        return self.username

class Distributor(models.Model):
    user                = models.ForeignKey(User, on_delete=models.CASCADE)
    brand               = models.CharField(max_length=100)
    ceo_name            = models.CharField(max_length=100)
    average_earnings    = models.PositiveIntegerField()
    company_created_At  = models.DateField(auto_now=False, auto_now_add=False)
    is_approveled       = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

herbco_env/herbco/apps/shop/models.py
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from shop.utils import unique_slug_generator
from profiles.models import Distributor

def item_upload_location(instance, filename):
    return "%s/%s" %(instance.slug, filename)

class Category(models.Model):
    name            = models.CharField(max_length=50)
    slug            = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:categories', kwargs={'slug': self.slug})

class Item(models.Model):
    owner           = models.ForeignKey(Distributor, on_delete=models.CASCADE)
    name            = models.CharField(max_length=200)
    slug            = models.SlugField(unique=True, blank=True)
    description     = models.TextField(default='') 
    price           = models.IntegerField(default=0)
    sold            = models.IntegerField(default=0)
    weight          = models.IntegerField(default=0)
    stock           = models.IntegerField(default=0)
    is_approvaled   = models.BooleanField(default=False)
    is_updated      = models.BooleanField(default=False)
    is_deleted      = models.BooleanField(default=False)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated_date    = models.DateTimeField(auto_now=True)
    category        = models.ForeignKey(Category)
    related_product = models.ForeignKey('Item', null=True, blank=True)
    # Image
    image           = models.ImageField(upload_to=item_upload_location, width_field='width_field', height_field='height_field')
    width_field     = models.IntegerField(default=0)
    height_field    = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail', kwargs={'slug': self.slug})

class ShoppingCart(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shopping_cart')
    items           = models.ManyToManyField(Item, blank=True, related_name='items')

    def __str__(self):
        return self.owner.username

class ItemExtra(models.Model):
    itemex          = models.OneToOneField(Item, related_name='itemex')
    shopcart        = models.ForeignKey(ShoppingCart)
    quantity        = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.itemex.name

class Order(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_cart       = models.ForeignKey(ShoppingCart)
    order_items     = models.ManyToManyField(Item, blank=True, related_name='order_items')

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.owner.username

class Comment(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment         = models.TextField(max_length=500)

@receiver(pre_save, sender=Item)
@receiver(pre_save, sender=Category)
def event_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

herbco_env/herbco/apps/shop/forms.py
from django import forms

from .models import Item

class ItemCreateForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = [
            'image',
            'name',
            'description',
            'price',
            'stock',
            'weight',
            'category',
            'related_product'
        ]
        help_texts = {
            'related_product': 'This is optional. If a product have a relation with other product use this one',
            'weight'         : 'Gram'
        }

herbco_env/herbco/apps/shop/templates/shop/category.html
{% extends "base.html" %}
{% block content %}
<div class="container">
{% if items|length == 0 %}
  <h4>There is no item in this category</h4>
{% else %}
<div class="col-9">
    <div class="row">
      {% for item in items %}
        <div class="col-sm-3">
          <div class="card mb-4">
            <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
              <span>${{ item.price }}</span>
              <a href="{% url 'shop:add_to_cart' item.id %}" class="btn btn-primary pull-right">Add
                <i class="fa fa-plus" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
  </div>
</div>
{% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/checkout.html
{% extends "base.html" %}
{% block content %}
  {% if items %}
  <div class="col-sm-6 mx-auto">
    <form method="post" action="{% url 'shop:checkout_final' %}">{% csrf_token %}
    <b><h2>Your Items : </h2></b>
    {% for item in items %}
    ({{item.itemex.quantity}})x<b>{{item.name}}</b><br>
    <input type="hidden" name="items" value="{{item.pk}}">
    {% endfor %}
    Total: ${{total}}
    <br>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab"
        data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Credit Cart</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab"
        data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Pay at the door
</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <div class="form-group">
      <label for="inputAddress">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="form-group">
      <label for="inputAddress2">Address 2</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text" class="form-control" id="inputCity">
      </div>
      <div class="form-group col-md-4">
        <label for="inputState">State</label>
        <select id="inputState" class="form-control">
          <option selected>Turkey</option>
          <option>USA</option>
        </select>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">Zip</label>
        <input type="text" class="form-control" id="inputZip">
      </div>
    </div>
    <div class="form-group">
      <label for="inputAddress">Credit Card</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="2545 5896 2445 2178">
    </div>
    <div class="form-group">
      <label for="inputAddress2">Credit Card Password</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="352">
    </div>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <div class="form-group">
      <label for="inputAddress">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="form-group">
      <label for="inputAddress2">Address 2</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text" class="form-control" id="inputCity">
      </div>
      <div class="form-group col-md-4">
        <label for="inputState">State</label>
        <select id="inputState" class="form-control">
          <option selected>Turkey</option>
          <option>USA</option>
        </select>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">Zip</label>
        <input type="text" class="form-control" id="inputZip">
      </div>
    </div>
  </div>
</div>

  <button type="submit" class="btn btn-primary">Check Out</button>
  <br><br>
</form>
  </div>
  {% else %}
    <h1>You don't have any item to CheckOut</h1>
  {% endif %}

{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/checkout_final.html
{% extends "base.html" %}
{% block content %}
<div class="col-6 mx-auto">
    Succesfully | Order Number: {{request.user.order_set.first.pk}}
    <br><br>
    <form action="{% url 'shop:comment' %}" method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="comment"><b>Comment:</b></label>
        <textarea name="comment" class="form-control" rows="5" id="comment"></textarea>
        <br>
        <button class="btn btn-primary" type="submit" name="button">Submit</button>
      </div>
    </form>
    <a href="/" class="btn btn-success" value="Go to Home Page">Go To Home Page</a>
</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/contact_us.html
{% extends "base.html" %}
{% block content %}

<div class="col-sm-12">
  <a href="{% url 'users:distributor_create' %}">Click Here</a>, If you want to be Distributor
</div>

{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/feedbacks.html
{% extends "base.html" %}
{% block content %}
  <div class="col-6 mx-auto">
    <ul>
      {% for feedback in feedbacks %}
        <li><b>From:</b> {{feedback.owner.username}};<br>
          <b>Comment:</b> {{feedback.comment}}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="col-sm-12 col-md-10 offset-md-1 col-lg-6 offset-lg-3">
    {% if user.user_type == '3' %}
      <h1>New Item Create</h1><br>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark" type="submit">Add Product</button>
      </form>
    {% else %}
      <h1>You are not a Distributor. You can not add Item</h1>
    {% endif %}
  </div>

{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_deleted.html
{% extends "base.html" %}
{% block content %}
<div class="col-12">
  {% if user.user_type == '1' %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Stock</th>
        <th scope="col">Is Approveled ?</th>
      </tr>
    </thead>
    {% for item in items_deleted %}
    <form action="{% url 'shop:confirm_deleted_item' %}" method="post">
      {% csrf_token %}
    <tbody>
      <tr>
        <th scope="row">{{ item.pk }}</th>
        <td>{{ item.name }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.stock }}</td>
        <td>
          <input type="checkbox" name="inputs" value="{{ item.pk }}"/>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <input class="btn btn-dark btn-right pull-right" type="submit" value="Approvel Selected İtems"></a>
  </form>
  {% else %}
    <h4>Only admin can access this page !</h4>
  {% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_detail.html
{% extends "base.html" %}

{% block content %}
<div class="col-9">
  {% if item.is_updated %}
    <h1>waiting for approvel</h1>
  {% endif %}
  {% if item.stock == 0 %}
  <h1>There is no stock for this product</h1><br>
  {% endif %}
  <form action="{% url 'shop:add_to_cart' item.id %}" method="post">{% csrf_token %}
  <img src="{{ item.image.url }}" alt="" width="175px", height="auto"><br>
  <h4>Item name: {{ item.name }}</h4>
  <br>
  <h4>Item price: {{ item.price }}</h4><br>
  <h4>Item Stock: {{ item.stock }}</h4><br>
  <h4>Item Description: {{ item.description }}</h4><br>
  <h4>Item Weight: {{ item.weight }} Gram</h4><br>
  {% if not item.stock == 0 %}
  <h4>Quantity: <input type="number" name="q" value="1" min="1" max="{{ item.stock }}"></h4>
  {% endif %}
  {% if item.related_product %}
    <h3>This item has a related product. If you want to buy <b>{{item.name}}</b>, you should also buy <b>{{item.related_product.name}}</b> ; </h3><br>
    <h4>Item name: {{ item.related_product.name }}</h4>
    <br>
    <h4>Item price: {{ item.related_product.price }}</h4>
    <h4>Item Stock: {{ item.related_product.stock }}</h4>
    <h4>Item Weight: {{ item.related_product.weight }} Gram</h4>
    <img src="{{ item.related_product.image.url }}" alt="" width="175px", height="auto">
  {% endif %}<br>
    <input
        type="submit"
        class="btn btn-primary {% if item.stock == 0 or item.is_updated %}disabled btn-dark{% endif %}"
        value="Add To Cart">
    </input>
</form>

</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_pending.html
{% extends "base.html" %}
{% block content %}
<div class="col-12">
  {% if user.user_type == '1' %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Stock</th>
        <th scope="col">Related Item</th>
        <th scope="col">Is Approveled ?</th>
      </tr>
    </thead>
    {% for item in items_pend %}
    <form action="{% url 'shop:confirm_item' %}" method="post">{% csrf_token %}
    <tbody>
      <tr>
        <th scope="row">{{ item.pk }}</th>
        <td>{{ item.name }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.stock }}</td>
        <td>
          {% if item.related_product %}
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">
            {{item.related_product.name}}
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{{item.related_product.name}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <div class="card mb-4">
                      <img class="card-img-top" src="{{ item.related_product.image.url }}" width="85px" height="130px">
                      <div class="card-body">
                        <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.related_product.name }}</a></h4>
                        <span>${{ item.related_product.price }}</span><br>
                        Description :
                        {% if item.description %}
                          {{item.related_product.description}}
                        {% else %}
                          None
                        {% endif %}<br>
                        Stock : {{ item.related_product.stock }}
                        </a>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </div>

          {% endif %}</td>
        <td>
          <input type="checkbox" name="inputs" value="{{ item.pk }}"/>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <input class="btn btn-danger" name="reject_items" type="submit" value="Reject Selected Items">
  <input class="btn btn-dark btn-right pull-right" name="accept_items" type="submit" value="Approvel Selected İtems">
  </form>
  {% else %}
    <h4>Only admin can access this page !</h4>
  {% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% if request.user.distributor_set.first == item.owner%}
<div class="col-sm-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Edit</button>
</form>
<br>
  {% if item.is_deleted %}
  <a href="{% url 'shop:add_again' item.pk%}" class="btn btn-warning">Add Again
  {% else %}
  <a href="{% url 'shop:item_delete' item.pk%}" class="btn btn-warning">Delete
  {% endif %}
</a>

</div>
{% else %}
  <h1>You are not owner for this item</h1>
{% endif %}
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/item_updated.html
{% extends "base.html" %}
{% block content %}
<div class="col-12">
  {% if user.user_type == '1' %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Stock</th>
        <th scope="col">Is Approveled ?</th>
      </tr>
    </thead>
    {% for item in items_updated %}
    <form action="{% url 'shop:confirm_u_item' %}" method="post">
      {% csrf_token %}
    <tbody>
      <tr>
        <th scope="row">{{ item.pk }}</th>
        <td>{{ item.name }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.stock }}</td>
        <td>
          <input type="checkbox" name="inputs" value="{{ item.pk }}"/>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <input class="btn btn-dark btn-right pull-right" type="submit" value="Approvel Selected İtems"></a>
  </form>
  {% else %}
    <h4>Only admin can access this page !</h4>
  {% endif %}
</div>
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/search.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-12">
      
    <div class="row">

      {% for item in items %}
        <div class="col-sm-3">
          <div class="card mb-4">
            <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
              <span>${{ item.price }}</span>
              <a href="{% url 'shop:add_to_cart' item.id %}" class="btn btn-primary pull-right">Add
                <i class="fa fa-plus" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
</div>

{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/shopping_cart.html
{% extends "base.html" %}
{% block content %}
{% if not request.user.user_type == '4' %}
  <h2>You are not customer!</h2>
{% elif cart_items.count == 0 %}
  <h2>There is no item in your shopping cart</h2>
{% else %}
<div class="col-sm-12">
  <h1>Shopping Cart</h1>
  <br>
  <div class="shopping-cart">
    <div class="column-labels">
      <label class="product-image">Image</label>
      <label class="product-details">Product</label>
      <label class="product-price">Price</label>
      <label class="product-quantity">Quantity</label>
      <label class="product-removal">Remove</label>
      <label class="product-line-price">Total & CheckOut</label>
    </div>

  {% for item in cart_items %}
    <div class="product">
      <div class="product-image">
        <img src="{{ item.image.url }}">
      </div>
      <div class="product-details">
        <h5>{{ item.name }}</h5>
      </div>
      <div class="product-price">{{ item.price }}</div>
      <div class="product-quantity">
        <input type="hidden" name="item" value="{{item.pk}}">
        <input id="q" name="quantity" type="number" value="{{item.itemex.quantity}}" min="1" max="{{ item.stock }}">
      </div>
      <div class="product-removal">
        <a href="{% url 'shop:delete_from_cart' item.id %}" class="btn btn-primary remove-product">
          Remove
        </a>
      </div>
      <div class="product-line-price">{{ item.price }}
      </div>
    </div>
  {% endfor %}
  <div class="totals">
    <div class="totals-item">
      <label>Subtotal</label>
      <div class="totals-value" id="cart-subtotal">0</div>
    </div>
    <div class="totals-item">
      <label>Tax (5%)</label>
      <div class="totals-value" id="cart-tax">0</div>
    </div>
    <div class="totals-item">
      <label>Shipping</label>
      <div class="totals-value" id="cart-shipping">0</div>
    </div>
    <div class="totals-item totals-item-total">
      <label>Grand Total</label>
      <div class="totals-value" id="cart-total">0</div>
    </div>
  </div>
  <a href="{% url 'shop:checkout' %}" class="checkout">Checkout</a>
  <a href="/" class="checkout mr-3" style="background:grey;">Continue Shopping</a>
  </div>
</div>
{% endif %}
{% endblock content %}

herbco_env/herbco/apps/shop/templates/shop/show_statics.html
{% extends "base.html" %}
{% block content %}
  {% for dist in distributors %}
  <div class="col-sm-12">
    <h4>Distributor name: {{dist}}</h4>
    {% if dist.item_set.all.count == 0 %}
    Distributor not have any item
    {% endif %}
    {% for item in dist.item_set.all %}
      Item Name: {{item.name}} | Item Sold: {{item.sold}}<br>
    {% endfor %}
    <br><br>
</div>
{% endfor %}
{% endblock content %}