FULL Pre/herbco/apps/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView ,LogoutView

from profiles.views import (
    UserLoginView,
    UserCreateView,
    DistributorCreateView,
    DistributorPendingListView,
    confirm_distributor, # FBV
    DistributorItemsListView,
)
urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', UserCreateView.as_view(), name='register'),
    url(r'^distributors/create/$', DistributorCreateView.as_view(), name='distributor_create'),
    url(r'^distributors/pending/$', DistributorPendingListView.as_view(), name='distributors'),
    url(r'^distributors/pending/confirm/$', confirm_distributor, name='distributor_confirm'),
    url(r'^distributors/my-items/$', DistributorItemsListView.as_view(), name='distributor_items'),

]

FULL Pre/herbco/apps/shop/urls.py
from django.conf.urls import url

from shop.views import (
    HomeView,
    ItemCreateView,
    ItemDetailView,
    ItemPendingListView,
    ShoppingCartListView,
    ContactUsTemplateView,
    confirm_item,
    confirm_u_item,
    add_to_cart,
    delete_from_cart,
    CategoryListView,
    ItemUpdatingListView,
    search,
    ItemUpdateView,
    CheckOut,
    item_delete,
    ItemDeletedListView,
    confirm_deleted_item,
    StaticsListView,
    checkout_final,
    MyOrdersListView,
    comment,
    FeedBacksListView,
    update_quantity,
    add_again,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/$', search, name='search'),
    url(r'^item/create/$', ItemCreateView.as_view(), name='create'),
    url(r'^item/item_delete/(?P<pk>\d+)/$', item_delete, name='item_delete'),
    url(r'^item/add_again/(?P<pk>\d+)/$', add_again, name='add_again'),
    url(r'^item/update/(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    url(r'^item/add/(?P<id>\d+)/$', add_to_cart, name='add_to_cart'),
    url(r'^item/delete/(?P<id>\d+)/$', delete_from_cart, name='delete_from_cart'),
    url(r'^item/(?P<slug>[-\w]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^items/pending/$', ItemPendingListView.as_view(), name='pending_items'),
    url(r'^items/updated/$', ItemUpdatingListView.as_view(), name='updated_items'),
    url(r'^items/deleted/$', ItemDeletedListView.as_view(), name='deleted_items'),
    url(r'^item/pending/confirm/$', confirm_item, name='confirm_item'),
    url(r'^item/updated/confirm/$', confirm_u_item, name='confirm_u_item'),
    url(r'^item/deleted/confirm/$', confirm_deleted_item, name='confirm_deleted_item'),
    url(r'^update_quantity/$', update_quantity, name='update_quantity'),
    url(r'^statics/$', StaticsListView.as_view(), name='statics'),
    url(r'^cart/$', ShoppingCartListView.as_view(), name='cart'),
    url(r'^cart/checkout/$', CheckOut.as_view(), name='checkout'),
    url(r'^cart/checkout/final/$', checkout_final, name='checkout_final'),
    url(r'^contact-us/$', ContactUsTemplateView.as_view(), name='contact_us'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryListView.as_view(), name='categories'),
    url(r'^my_orders/$', MyOrdersListView.as_view(), name='my_orders'),
    url(r'^feedbacks/$', FeedBacksListView.as_view(), name='feedbacks'),
    url(r'^comment/done/$', comment, name='comment'),
]

FULL Pre/herbco/herbco/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# For development
from django.conf import settings
from django.conf.urls.static import static
# For development

urlpatterns = [
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^users/', include('profiles.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FULL Pre/herbco/apps/shop/models.py
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from shop.utils import unique_slug_generator
from profiles.models import Distributor

def item_upload_location(instance, filename):
    return "%s/%s" %(instance.slug, filename)

class Category(models.Model):
    name            = models.CharField(max_length=50)
    slug            = models.SlugField(unique=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:categories', kwargs={'slug': self.slug})

class Item(models.Model):
    owner           = models.ForeignKey(Distributor, on_delete=models.CASCADE)
    name            = models.CharField(max_length=200)
    slug            = models.SlugField(unique=True, blank=True)
    description     = models.TextField(default='') 
    price           = models.IntegerField(default=0)
    sold            = models.IntegerField(default=0)
    weight          = models.IntegerField(default=0)
    stock           = models.IntegerField(default=0)
    is_approvaled   = models.BooleanField(default=False)
    is_updated      = models.BooleanField(default=False)
    is_deleted      = models.BooleanField(default=False)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated_date    = models.DateTimeField(auto_now=True)
    category        = models.ForeignKey(Category)
    related_product = models.ForeignKey('Item', null=True, blank=True)
    # Image
    image           = models.ImageField(upload_to=item_upload_location, width_field='width_field', height_field='height_field')
    width_field     = models.IntegerField(default=0)
    height_field    = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail', kwargs={'slug': self.slug})

class ShoppingCart(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shopping_cart')
    items           = models.ManyToManyField(Item, blank=True, related_name='items')

    def __str__(self):
        return self.owner.username

class ItemExtra(models.Model):
    itemex          = models.OneToOneField(Item, related_name='itemex')
    shopcart        = models.ForeignKey(ShoppingCart)
    quantity        = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.itemex.name

class Order(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    shop_cart       = models.ForeignKey(ShoppingCart)
    order_items     = models.ManyToManyField(Item, blank=True, related_name='order_items')

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.owner.username

class Comment(models.Model):
    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment         = models.TextField(max_length=500)

@receiver(pre_save, sender=Item)
@receiver(pre_save, sender=Category)
def event_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

FULL Pre/herbco/apps/shop/forms.py
from django import forms

from .models import Item

class ItemCreateForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = [
            'image',
            'name',
            'description',
            'price',
            'stock',
            'weight',
            'category',
            'related_product'
        ]
        help_texts = {
            'related_product': 'This is optional. If a product have a relation with other product use this one',
            'weight'         : 'Gram'
        }

FULL Pre/herbco/apps/shop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.generic import (
    ListView,
    CreateView,
    FormView,
    DetailView,
    TemplateView,
    UpdateView,
)

from shop.models import Item, ShoppingCart, Category, ItemExtra, Order, Comment
from profiles.models import Distributor
from .forms import ItemCreateForm

def search(request):
    search = request.GET.get("search")
    category_id = request.GET.get("category")
    queryset = None
    if search:
        queryset = Item.objects.filter(is_approvaled=True).filter(is_updated=False).filter(is_deleted=False)
        queryset = queryset.filter(name__icontains=search)
        if not category_id == '0':
            category = get_object_or_404(Category, pk=category_id)
            queryset = queryset.filter(category=category)
        if not queryset:
            messages.warning(request, 'There is no item with these search')
            return HttpResponseRedirect("/")
    else:
        messages.warning(request, 'You have to write something to search !!')
        return HttpResponseRedirect("/")
    context = {
        'items': queryset,
        'categories': Category.objects.all()
    }
    return render(request, 'shop/search.html', context)

@login_required(redirect_field_name='/users/login')
def confirm_item(request):
    if request.method == 'POST':
        list_of_input_ids = request.POST.getlist('inputs')
        for item_id in list_of_input_ids:
            item_id = get_object_or_404(Item, pk=item_id)
            if 'reject_items' in request.POST:
                item_id.delete()
            elif 'accept_items' in request.POST:
                item_id.is_approvaled = True
                item_id.save()
    return HttpResponseRedirect('/items/pending/')

@login_required(redirect_field_name='/users/login')
def confirm_u_item(request):
    if request.method == 'POST':
        list_of_input_ids = request.POST.getlist('inputs')
        for item_id in list_of_input_ids:
            item_id = get_object_or_404(Item, pk=item_id)
            item_id.is_updated = False
            item_id.save()
    return HttpResponseRedirect('/items/updated/')

@login_required(redirect_field_name='/users/login')
def confirm_deleted_item(request):
    if request.method == 'POST':
        list_of_input_ids = request.POST.getlist('inputs')
        for item_id in list_of_input_ids:
            item_id = get_object_or_404(Item, pk=item_id)
            item_id.delete()
    return HttpResponseRedirect('/items/deleted/')

class HomeView(ListView):
    template_name = 'shop/home.html'
    queryset = Item.objects.filter(is_approvaled=True).filter(is_updated=False).filter(is_deleted=False)
    context_object_name = 'items'

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(*args ,**kwargs)
        queryset_last_5 = Item.objects.filter(is_approvaled=True).filter(is_updated=False).filter(is_deleted=False).order_by('-timestamp')[:5]
        queryset_best_seller = Item.objects.filter(is_approvaled=True).filter(is_updated=False).filter(is_deleted=False).order_by('-sold')[:5]
        context['lastfive'] = queryset_last_5
        context['bestseller'] = queryset_best_seller
        context['dist_count'] = Distributor.objects.filter(is_approveled=False).count()
        context['item_count'] = Item.objects.filter(is_approvaled=False).filter(is_deleted=False).count()
        context['item_u_count'] = Item.objects.filter(is_updated=True).filter(is_deleted=False).count()
        context['item_delete_count'] = Item.objects.filter(is_deleted=True).count()
        context['categories'] = Category.objects.all()
        return context

class ContactUsTemplateView(TemplateView):
    template_name = "shop/contact_us.html"

class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'shop/item_create.html'
    form_class = ItemCreateForm
    success_url = '/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user.distributor_set.first()
        return super(ItemCreateView, self).form_valid(form)

class ItemDetailView(DetailView):
    template_name = "shop/item_detail.html"
    context_object_name = 'item'

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Item, slug=slug)
        return obj

class ItemPendingListView(LoginRequiredMixin, ListView):
    template_name = 'shop/item_pending.html'
    queryset = Item.objects.filter(is_approvaled=False)
    context_object_name = 'items_pend'

    def get_context_data(self, *args, **kwargs):
        context = super(ItemPendingListView, self).get_context_data(*args ,**kwargs)
        context['item_count'] = Item.objects.filter(is_approvaled=False).filter(is_deleted=False).count()
        return context

class ItemDeletedListView(LoginRequiredMixin, ListView):
    template_name = 'shop/item_deleted.html'
    queryset = Item.objects.filter(is_deleted=True)
    context_object_name = 'items_deleted'

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'shop/item_update.html'
    model = Item
    fields = [
        'name',
        'stock',
        'price',
    ]

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.is_updated = True
        return super(ItemUpdateView, self).form_valid(form)

class ItemUpdatingListView(LoginRequiredMixin, ListView):
    template_name = 'shop/item_updated.html'
    queryset = Item.objects.filter(is_updated=True).filter(is_deleted=False)
    context_object_name = 'items_updated'

@login_required(redirect_field_name='/users/login')
def item_delete(request, pk=None):
    item = get_object_or_404(Item, pk=pk)
    if request.user.distributor_set.first() == item.owner:
        item.is_deleted = True
        item.is_approvaled = False
        item.save()
        messages.info(request, 'We send a request to delete your item')
    else:
        messages.warning(request, 'You are not owner for this item')
    return HttpResponseRedirect("/users/distributors/my-items/")

@login_required(redirect_field_name='/users/login')
def add_again(request, pk=None):
    item = get_object_or_404(Item, pk=pk)
    if request.user.distributor_set.first() == item.owner:
        item.is_deleted = False
        item.save()
        messages.info(request, 'We send a request to delete your item')
    else:
        messages.warning(request, 'You are not owner for this item')
    return HttpResponseRedirect("/users/distributors/my-items/")

@login_required(redirect_field_name='/users/login')
def add_to_cart(request, id=None):
    if not request.user.user_type == '4':
        messages.warning(request, 'You are not customer, so you cannot add to basket any item')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    item = get_object_or_404(Item, pk=id)
    quantity = request.POST.get("q", 1)
    if item.stock == 0:
        messages.warning(request, 'There is no stock for this product')
    else:
        shop_cart = get_object_or_404(ShoppingCart, owner=request.user)
        if item in shop_cart.items.all():
            messages.warning(request, 'This item is already in your basket')
        else:
            shop_cart.items.add(item)
            ItemExtra.objects.get_or_create(itemex=item, shopcart=shop_cart, quantity=quantity)
            if item.related_product:
                r_item = get_object_or_404(Item, pk=item.related_product.pk)
                shop_cart.items.add(r_item)
                ItemExtra.objects.get_or_create(itemex=r_item, shopcart=shop_cart, quantity=quantity)
                messages.success(request, 'Related item add you basket.')
            messages.success(request, 'Item added to your basket.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required(redirect_field_name='/users/login')
def delete_from_cart(request, id=None):
    item = get_object_or_404(Item, pk=id)
    shop_cart = get_object_or_404(ShoppingCart, owner=request.user)
    itemex = get_object_or_404(ItemExtra, itemex=item, shopcart=shop_cart)
    if item.item_set.all():
        for i in item.item_set.all():
            if i in shop_cart.items.all():
                i_ex = get_object_or_404(ItemExtra, itemex=i, shopcart=shop_cart)
                i_ex.delete()
                shop_cart.items.remove(i)
    itemex.delete()
    shop_cart.items.remove(item)
    return HttpResponseRedirect("/cart")

class ShoppingCartListView(LoginRequiredMixin, ListView):
    template_name = "shop/shopping_cart.html"
    context_object_name = 'cart_items'
    def get_queryset(self):
        cart = ShoppingCart.objects.get(owner=self.request.user)
        queryset = cart.items.filter(is_updated=False).filter(is_deleted=False)
        return queryset

class CategoryListView(ListView):
    template_name = "shop/category.html"
    context_object_name = 'items'

    def get_queryset(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        category = Category.objects.get(slug=slug)
        queryset = Item.objects.filter(category=category).filter(is_deleted=False)
        return queryset

class CheckOut(LoginRequiredMixin, ListView):
    template_name = "shop/checkout.html"
    context_object_name = 'items'

    def get_queryset(self):
        cart = ShoppingCart.objects.get(owner=self.request.user)
        queryset = cart.items.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(CheckOut, self).get_context_data(*args ,**kwargs)
        total = 0
        queryset = self.get_queryset()
        for item in queryset:
            total += item.price

FULL Pre/herbco/apps/shop/templates/shop/category.html
{% extends "base.html" %}
{% block content %}
<div class="container">
{% if items|length == 0 %}
  <h4>There is no item in this category</h4>
{% else %}
<div class="col-9">
    <div class="row">
      {% for item in items %}
        <div class="col-sm-3">
          <div class="card mb-4">
            <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
            <div class="card-body">
              <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
              <span>${{ item.price }}</span>
              <a href="{% url 'shop:add_to_cart' item.id %}" class="btn btn-primary pull-right">Add
                <i class="fa fa-plus" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
  </div>
</div>
{% endif %}
</div>
{% endblock content %}

FULL Pre/herbco/apps/shop/templates/shop/checkout_final.html
{% extends "base.html" %}
{% block content %}
<div class="col-6 mx-auto">
    Succesfully | Order Number: {{request.user.order_set.first.pk}}
    <br><br>
    <form action="{% url 'shop:comment' %}" method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="comment"><b>Comment:</b></label>
        <textarea name="comment" class="form-control" rows="5" id="comment"></textarea>
        <br>
        <button class="btn btn-primary" type="submit" name="button">Submit</button>
      </div>
    </form>
    <a href="/" class="btn btn-success" value="Go to Home Page">Go To Home Page</a>
</div>
{% endblock content %}

FULL Pre/herbco/apps/shop/templates/shop/feedbacks.html
{% extends "base.html" %}
{% block content %}
  <div class="col-6 mx-auto">
    <ul>
      {% for feedback in feedbacks %}
        <li><b>From:</b> {{feedback.owner.username}};<br>
          <b>Comment:</b> {{feedback.comment}}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}

FULL Pre/herbco/apps/shop/templates/shop/home.html
{% extends "base.html" %}
{% block content %}
    <!-- Left-Side -->
    <div class="col-sm-3">
      <div class="card">
        <div class="card-header"><b>Categories</b></div>
        <ul class="list-group list-group-flush">
          {% for category in categories %}
          <li class="list-group-item"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <!-- Middle-Side -->
    <div class="col-md-6">
        <div class="row">
          {% for item in items %}
            <div class="col-sm-3">
              <div class="card mb-4">
                <img class="card-img-top" src="{{ item.image.url }}" width="85px" height="130px">
                <div class="card-body">
                  <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h4>
                  {% if item.stock == 0 %}
                  <h6><b>TÜKENDİ</b></h6>
                  {% endif %}
                  {% if not item.related_product %}
                  <span>${{ item.price }}</span>
                    {% if not item.stock == 0 %}
                    <a href="{% url 'shop:add_to_cart' item.id %}" class="btn btn-{% if item.stock == 0 %}dark{% else %}primary{% endif %} pull-right">Add
                      <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                    {% endif %}
                  {% else %}
                  <!-- Button trigger modal -->
                  <span>${{ item.price }}</span>
                  <button type="button" class="btn btn-{% if item.stock == 0 %}dark{% else %}primary{% endif %} pull-right" data-toggle="modal" data-target="#{{item.pk}}">
                    Add <i class="fa fa-plus" aria-hidden="true"></i>
                  </button>

                  <!-- Modal -->
                  <div class="modal fade" id="{{ item.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLongTitle">{{ item.related_product.name }}</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <h4>This item has related product</h4>
                          <h5>İf you want to buy {{ item.name }}, You have to buy {{ item.related_product.name }}</h5>
                          <h6>Item name: {{ item.related_product.name }}</h6>
                          <h6>Item price: {{ item.related_product.price }}</h6>
                          <h6>Item Stock: {{ item.related_product.stock }}</h6>
                          <h6>Item Weight: {{ item.related_product.weight }} Gram</h6>
                          <img src="{{ item.related_product.image.url }}" alt="" width="175px", height="auto">
                        </div>
                        <div class="modal-footer">
                          <a href="{% url 'shop:add_to_cart' item.id %}" class="btn btn-{% if item.stock == 0 %}dark{% else %}primary{% endif %} pull-right">Add
                            <i class="fa fa-plus" aria-hidden="true"></i>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
      </div>
    </div>
    <!-- Right Side -->
    <div class="col-md-3">
      <!-- Admin Panel -->
      {% if user.user_type == '1' %}
      <div class="card mb-3">
        <div class="card-header"><b>Admin</b><br><small>Only Admin can see here</small></div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <a href="{% url 'shop:pending_items' %}">
              <span class="badge badge-pill badge-danger">{{ item_count }}</span> Confirm Item
            </a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'shop:updated_items' %}">
              <span class="badge badge-pill badge-danger">{{ item_u_count }}</span> Update Item
            </a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'shop:feedbacks' %}">
              Show Feedbacks
            </a>
          </li>
        </ul>
      </div>
      <!-- Manager Panel -->
      {% elif user.user_type == '2' %}
      <div class="card mb-3">
        <div class="card-header"><b>Manager</b><br><small>Only Manager can see here</small></div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><a href="{% url 'users:distributors' %}">
            <span class="badge badge-pill badge-danger">{{ dist_count }}</span> Confirm Distributor</a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'shop:statics' %}">
              Show Statics
            </a>
          </li>
        </ul>
      </div>
      <!-- Distributor Panel -->
      {% elif user.user_type == '3' %}
      <div class="card mb-3">
        <div class="card-header"><b>Distributor</b><br><small>Only Distributor can see here</small></div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <a href="{% url 'shop:create' %}">Add New Item</a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'users:distributor_items' %}">My Items</a>
          </li>
        </ul>
      </div>
      {% endif %}

      <!-- Best Seller -->
      <div class="card mb-3">
        <div class="card-header"><b>Best Seller</b></div>
        <ul class="list-group list-group-flush">
          {% for best in bestseller %}
            <li class="list-group-item"><a href="{{ best.get_absolute_url }}">{{ best.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <!-- Last Products -->
      <div class="card mb-3">
        <div class="card-header"><b>Last Products</b></div>
        <ul class="list-group list-group-flush">
          {% for lastitem in lastfive %}
            <li class="list-group-item"><a href="{{ lastitem.get_absolute_url }}">{{ lastitem.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
{% endblock content %}

FULL Pre/herbco/apps/shop/templates/shop/shopping_cart.html
{% extends "base.html" %}
{% block content %}
{% if not request.user.user_type == '4' %}
  <h2>You are not customer!</h2>
{% elif cart_items.count == 0 %}
  <h2>There is no item in your shopping cart</h2>
{% else %}
<div class="col-sm-12">
  <h1>Shopping Cart</h1>
  <br>
  <div class="shopping-cart">
    <div class="column-labels">
      <label class="product-image">Image</label>
      <label class="product-details">Product</label>
      <label class="product-price">Price</label>
      <label class="product-quantity">Quantity</label>
      <label class="product-removal">Remove</label>
      <label class="product-line-price">Total & CheckOut</label>
    </div>

  {% for item in cart_items %}
    <div class="product">
      <div class="product-image">
        <img src="{{ item.image.url }}">
      </div>
      <div class="product-details">
        <h5>{{ item.name }}</h5>
      </div>
      <div class="product-price">{{ item.price }}</div>
      <div class="product-quantity">
        <input type="hidden" name="item" value="{{item.pk}}">
        <input id="q" name="quantity" type="number" value="{{item.itemex.quantity}}" min="1" max="{{ item.stock }}">
      </div>
      <div class="product-removal">
        <a href="{% url 'shop:delete_from_cart' item.id %}" class="btn btn-primary remove-product">
          Remove
        </a>
      </div>
      <div class="product-line-price">{{ item.price }}
      </div>
    </div>
  {% endfor %}
  <div class="totals">
    <div class="totals-item">
      <label>Subtotal</label>
      <div class="totals-value" id="cart-subtotal">0</div>
    </div>
    <div class="totals-item">
      <label>Tax (5%)</label>
      <div class="totals-value" id="cart-tax">0</div>
    </div>
    <div class="totals-item">
      <label>Shipping</label>
      <div class="totals-value" id="cart-shipping">0</div>
    </div>
    <div class="totals-item totals-item-total">
      <label>Grand Total</label>
      <div class="totals-value" id="cart-total">0</div>
    </div>
  </div>
  <a href="{% url 'shop:checkout' %}" class="checkout">Checkout</a>
  <a href="/" class="checkout mr-3" style="background:grey;">Continue Shopping</a>
  </div>
</div>
{% endif %}
{% endblock content %}